site_name: TACC MkDocs Theme
site_description: Styles for TACC Documentation
site_author: Wesley Bomar
# site_url: https://docs.tacc.utexas.edu
repo_url: https://github.com/TACC/Core-Docs
edit_uri: edit/main/docs/

theme:
  name: tacc_readthedocs
  hljs_languages:
    - yaml
    - shell
extra_css:
  - css/tacc-theme.css
extra_javascript:
  - js/tacc-theme.js

nav:
  - Getting Started:
    - Quick Start: index.md
    - Configure: configure.md
    - Customize: customize.md
  - Examples:
    - Basic: clients/basic-example.md
    - TACC Docs: clients/tacc-docs-example.md
    - DS User Guide: clients/ds-user-guide-example.md

plugins:
  - search
  - macros # allows {% include ... %} (and macros)

# https://python-markdown.github.io/extensions/
markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr
  # Enabled by MkDocs by default
  # https://github.com/mkdocs/mkdocs/blob/1.4.2/docs/user-guide/configuration.md#markdown_extensions
  # - meta
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading
      # WARNING: Requires MkDocs v1.5
      # https://github.com/mkdocs/mkdocs/blob/1.5.0/pyproject.toml#L39
      # permalink_leading: true
  # - tables
  # - fenced_code
  # Extensions from PyMdown
  # https://facelessuser.github.io/pymdown-extensions
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
    # There is an alternative style that supports experimental mobile UX
    # SEE: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#alternate-style
  - pymdownx.blocks.html
  # FAQ: The `pymdownx.highlight` is useful only if Pygments is installed
  #      because Pygments would offer:
  #      - build-time syntax highlight markup
  #      - custom language tags and formatters
  # WARNING: Installing Pygments causes MkDocs build error
  # - pymdownx.highlight
  #     use_pygments: true
