site_name: TACC MkDocs Theme
site_description: Styles for TACC Documentation
site_author: Wesley Bomar
# site_url: https://docs.tacc.utexas.edu
repo_url: https://github.com/TACC/Core-Docs
edit_uri: edit/main/docs/

theme:
  name: tacc_readthedocs
  hljs_languages:
    - yaml
    - shell
  # "ReadTheDocs" Theme Features
  logo: img/logo.svg
  # "TACC" Theme Features
  cms_url: https://github.com/TACC/Core-Docs
  cms_name: TACC/Core-Docs
extra_css:
  - css/tacc-theme.css
extra_javascript:
  - js/tacc-theme.mjs

nav:
  - Getting Started:
    - Quick Start: index.md
    - Configuration: configure.md
    - Customization: customize.md
    - Extensions: extensions.md
  - Examples:
    - Basic: clients/basic-example.md
    - TACC Docs: clients/tacc-docs-example.md
    - DS User Guide: clients/ds-user-guide-example.md

plugins:
  - search

markdown_extensions:
  # Python-Markdown Extensions
  # https://python-markdown.github.io/extensions/
  - extra
  - admonition
  - nl2br
  # Python-Markdown Extensions: Enabled by MkDocs
  # https://github.com/mkdocs/mkdocs/blob/1.4.2/docs/user-guide/configuration.md#markdown_extensions
  # - meta
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading
      toc_depth: 2-6
      # WARNING: Requires MkDocs v1.5
      # https://github.com/mkdocs/mkdocs/blob/1.5.0/pyproject.toml#L39
      # permalink_leading: true
  # PyMDown Extensions
  # https://facelessuser.github.io/pymdown-extensions
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
